### ISSUE TITLE
Support Singularity 3.*?

### ISSUE THREAD

**Issue by rpwagner** [singularityhub/travis-ci#1]
Hi!

Any suggestions on how to update this to handle Singularity 3.0+ without resorting to Docker? I tried but got stuck dealing with Go inside of Travis CI.

Thanks

--Rick

**Comment by vsoch** [comment]
Yeah! I’ll give it a go (no pun intended) tomorrow. Stay tuned :)

**Comment by rpwagner** [comment]
Thank you!

**Comment by vsoch** [comment]
All set @rpwagner - give it a go! :)

https://github.com/singularityhub/travis-ci/pull/2

If you need the previous (legacy) Singularity, it's now on the release/2.6 branch.

**Comment by rpwagner** [comment]
Awesome! Thank you!
